### ISSUE TITLE
head is struggling to read files from /proc

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5703] opened 2023-12-24 09:18 UTC
The following will work:
```
$ cp /proc/version copy              
$  ./target/debug/coreutils head -c -1 copy 
Linux version 6.5.0-4-amd64 (debian-kernel@lists.debian.org) (gcc-13 (Debian 13.2.0-6) 13.2.0, GNU ld (GNU Binutils for Debian) 2.41) #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1 (2023-11-03)
```

while the following is failing:

```
$ ./target/debug/coreutils head -c -1 /proc/version
```

with GNU:
```
$ /usr/bin/head -c -1 /proc/version
Linux version 6.5.0-4-amd64 (debian-kernel@lists.debian.org) (gcc-13 (Debian 13.2.0-6) 13.2.0, GNU ld (GNU Binutils for Debian) 2.41) #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1 (2023-11-03)
```

**Comment by cre4ture** [comment] 2023-12-27 11:11
I can reproduce the issue. So I'll give it a try. :-)

**Comment by cakebaker** [comment] 2024-01-09 09:17
Closing this issue because it has been fixed in https://github.com/uutils/coreutils/pull/5732

**Closed by cakebaker** 2024-01-09 09:17 UTC
Labels: U - head, good first issue
