### ISSUE TITLE
```timeout``` Need better error message 

### ISSUE THREAD

**Issue by NEUZhangy** [uutils/coreutils#3040] opened 2022-02-03 00:58 UTC
$ ./timeout "" ""
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "empty string"', src/uu/timeout/src/timeout.rs:79:88
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by tertsdiepraam** [comment] 2022-02-03 07:45
Thank you for reporting these! Could you split this up into one issue per panic? They seem to be caused by different things, so it would be nice to tackle them one at a time.

**Comment by NEUZhangy** [comment] 2022-02-03 14:20
sure! I split them into 4 including this one.

**Comment by tertsdiepraam** [comment] 2022-02-03 14:47
Thanks!

**Comment by 353fc443** [comment] 2022-03-07 05:27
Fixed by #3206

**Closed** 2022-04-19 08:14 UTC
Labels: good first issue
