### ISSUE TITLE
`tests/misc/timeout.sh` fails intermittently

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4295] opened 2023-01-22 20:58 UTC
https://github.com/uutils/coreutils/actions/runs/3892703206

```
2023-01-11T12:54:36.0754239Z FAIL: tests/misc/timeout 
2023-01-11T12:54:36.0754314Z ======================== 
2023-01-11T12:54:36.0754320Z  
2023-01-11T12:54:36.0754425Z timeout: No such process (os error 3) 
2023-01-11T12:54:36.0754544Z FAIL tests/misc/timeout.sh (exit status: 1)
```

**Comment by jfinkels** [comment] 2023-02-18 16:25
Looks like a duplicate of #4124.

**Closed by jfinkels** 2023-02-18 16:25 UTC
