### ISSUE TITLE
'sort' still not fixed

### ISSUE THREAD

**Issue by Sanmayce** [uutils/coreutils#5521] opened 2023-11-10 19:34 UTC
Wanted to include coreutils' sort into a benchmark, still cannot:
```
[sanmayce@djudjeto3 Schmekerezada_no-corpora]$ LC_ALL=C
[sanmayce@djudjeto3 Schmekerezada_no-corpora]$ echo $LC_ALL
C
[sanmayce@djudjeto3 Schmekerezada_no-corpora]$ perf stat -d ./coreutils-0.0.22-x86_64-unknown-linux-gnu sort linux-6.6.1.tar -o cu
sort: invalid utf-8 sequence of 1 bytes from index 35495946

 Performance counter stats for './coreutils-0.0.22-x86_64-unknown-linux-gnu sort linux-6.6.1.tar -o cu':

            188.08 msec task-clock:u                     #    0.988 CPUs utilized             
                 0      context-switches:u               #    0.000 /sec                      
                 0      cpu-migrations:u                 #    0.000 /sec                      
            24,726      page-faults:u                    #  131.465 K/sec                     
        60,411,853      cycles:u                         #    0.321 GHz                         (56.74%)
        17,415,004      instructions:u                   #    0.29  insn per cycle              (71.22%)
         7,621,709      branches:u                       #   40.524 M/sec                       (71.53%)
            22,775      branch-misses:u                  #    0.30% of all branches             (71.74%)
         4,436,252      L1-dcache-loads:u                #   23.587 M/sec                       (70.96%)
   <not supported>      L1-dcache-load-misses:u                                               
           267,081      LLC-loads:u                      #    1.420 M/sec                       (71.55%)
            34,123      LLC-load-misses:u                #   12.78% of all L1-icache accesses   (57.66%)

       0.190383240 seconds time elapsed

       0.026275000 seconds user
       0.159013000 seconds sys

[sanmayce@djudjeto3 Schmekerezada_no-corpora]$ 
```

**Comment by tertsdiepraam** [comment] 2023-11-11 12:51
So this is the same issue as you opened before right? https://github.com/uutils/coreutils/issues/4049

Mind if I close this one as a duplicate?

**Comment by Sanmayce** [comment] 2023-11-11 14:09
> Mind if I close this one as a duplicate?

Sure, won't bother you again, just wanted to see whether fix is coming.

**Comment by tertsdiepraam** [comment] 2023-11-11 14:14
I just gave it a quick try, but it's tricky, because `str` (which requires valid utf-8) is used throughout the utility, but it should indeed be fixed.

**Comment by tertsdiepraam** [comment] 2023-11-11 14:15
Duplicate of https://github.com/uutils/coreutils/issues/4049

**Closed by tertsdiepraam** 2023-11-11 14:15 UTC
Labels: U - sort
