### ISSUE TITLE
ls: `-L` on broken links should return 1

### ISSUE THREAD

**Issue by jtracey** [uutils/coreutils#2928] opened 2022-01-27 18:29 UTC
`ls` is supposed to have an exit status of 1 for "minor problems". This includes trying to dereference symbolic links (via `-L`) when they don't link anywhere. The lack of return code is causing the latest `tests/ls/selinux-segfault` GNU test to fail.

**Comment by tertsdiepraam** [comment] 2022-01-27 23:03
The call that should return 1, according to the GNU test, is specifically:
```  
ls -L -Z
```
We already return 1 with:
```
ls -L -l
```
Or any other case where we try to deference the a broken symlink. I believe (but am not sure) that the issue is that because the security context is not supported in the first place, we never get the metadata, so we don't show the error.

**Comment by kimono-koans** [comment] 2022-01-28 15:59
`ls` seems like it needs a meta-thread for its issues.  Is OP implementing this?

**Comment by sylvestre** [comment] 2022-01-28 16:01
sure, please open as many issues as you need :)

**Comment by jtracey** [comment] 2023-01-30 04:12
This is still an issue.

>We already return 1 with:
>`ls -L -l`
>Or any other case where we try to deference the a broken symlink.

I'm still seeing ret code 0 with just `ls -L` for us, and ret code 1 on GNU.

**Comment by granquet** [comment] 2023-06-08 10:06
I've looked into it and think I've solved the `ls -L -Z` issue.

Though with GNU coreutils 9.1, I see `ls -L` returns 0, which is aligned with the behaviour I see in uutils ?

**Comment by tertsdiepraam** [comment] 2023-06-08 10:46
uutils `ls -L` is returning 0 for me. Which case is incompatible exactly?

**Comment by granquet** [comment] 2023-06-08 12:19
`ls -L -Z`
* returns 0 in uutils
* returns 1 in GNU coreutils
Attempting to fix this case with : https://github.com/uutils/coreutils/pull/4960

`ls -L` returns 0 on both, @jtracey seemed to imply that `ls -L` should return 1 too?

**Comment by tertsdiepraam** [comment] 2023-06-08 12:43
Ah sorry, I misread your comment. I think you're right!

**Comment by cakebaker** [comment] 2023-07-01 13:26
Fixed in https://github.com/uutils/coreutils/pull/4960

**Closed by cakebaker** 2023-07-01 13:26 UTC
Labels: U - ls, good first issue
