### ISSUE TITLE
du on Windows

### ISSUE THREAD

**Issue by garyemerson** [uutils/coreutils#1152] opened 2018-03-10 06:21 UTC
I'd be interested in having `du` compile on Windows. Looking at the code and compiler error msgs the only blocker is the use of `std::os::unix::fs::MetadataExt`. Seems like that could be fixed with a handful of `#[cfg]`'s. That would of course affect parts of the code that use `MetadataExt` and ultimately would lead to the following options not being included on Windows:
* apparent-size
* time
* time-style
* count-links

I'd personally still get use out of a `du` without these options. I'm down to work on this if ppl are open to these sorta changes.

**Comment by Arcterus** [comment] 2018-03-10 07:52
These sorts of changes are always welcome!  Of course, if you manage to figure out how to get the equivalent info on Windows that would be preferable to disabling features, but ideally all the utils should be able to run in some form on any OS.

**Comment by Freaky** [comment] 2020-05-30 22:28
My [filesize crate](https://crates.io/crates/filesize) may be of interest - it's already used by several Rust `du`-alikes and abstracts across Windows and Unix.

**Comment by paulotten** [comment] 2021-04-06 22:57
Recommend marking as a duplicate of #1622 (which I implemented).

**Comment by cakebaker** [comment] 2023-09-19 14:25
Closing this ticket, fixed in https://github.com/uutils/coreutils/pull/1788

**Closed by cakebaker** 2023-09-19 14:25 UTC
