### ISSUE TITLE
`touch`: `test_du::test_du_time` fails on wrong date

### ISSUE THREAD

**Issue by Joining7943** [uutils/coreutils#4236] opened 2022-12-13 19:53 UTC
I ran the whole test suite on my linux machine and the `test_du::test_du_time` test fails with

```
--- test_du::test_du_time stdout ----
current_directory_resolved: 
run: /home/lenny/workspace/external/uutils/uutils/target/debug/coreutils touch -a -t 201505150000 date_test
run: /home/lenny/workspace/external/uutils/uutils/target/debug/coreutils touch -m -t 201606160000 date_test
run: /home/lenny/workspace/external/uutils/uutils/target/debug/coreutils du --time date_test
thread 'test_du::test_du_time' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<0      2016-06-16 01:00        date_test
>0      2016-06-16 00:00        date_test
 

', tests/common/util.rs:241:9
```

if I run the above commands manually with gnu's `touch`

```
❯ touch -a -t 201505150000 ../date_test
❯ touch -m -t 201606160000 ../date_test
❯ du --time ../date_test
0       2016-06-16 00:00        ../date_test
❯ target/debug/coreutils du --time ../date_test
0       2016-06-16 00:00        ../date_test
```

everything is alright. In a run with uutils only:

```
❯ target/debug/coreutils touch -a -t 201505150000 ../date_test
❯ target/debug/coreutils touch -m -t 201606160000 ../date_test
❯ target/debug/coreutils du --time ../date_test
0       2016-06-16 01:00        ../date_test
```

and I'm getting the wrong output from the test. Here's additionally the output of `stat` from the last (uutils) run :

```
❯ stat ../date_test 
  File: ../date_test
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 254,6   Inode: 10951300    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   lenny)   Gid: ( 1000/   lenny)
Access: 2015-05-15 01:00:00.000000000 +0200
Modify: 2016-06-16 01:00:00.000000000 +0200
Change: 2022-12-13 20:33:00.390171394 +0100
 Birth: 2022-12-13 20:30:20.546849071 +0100
```

**Comment by kralo** [comment] 2024-06-21 21:15
the test passes, cannot reproduce / looks fixed.
```
# date
Mi 11. Mär 18:56:33 EDT 2020
#  target/debug/coreutils touch -a -t 201505150000 ../date_test
#  target/debug/coreutils touch -m -t 201606160000 ../date_test
#  target/debug/coreutils du --time ../date_test
0	2016-06-16 00:00	../date_test
#  target/debug/coreutils du --version
du 0.0.26
```
Who might be able to close this?

**Comment by cakebaker** [comment] 2024-06-22 12:44
Closing this issue as it looks like it has been fixed in the meantime.

**Closed by cakebaker** 2024-06-22 12:44 UTC
Labels: U - touch
