### ISSUE TITLE
tests for factor are failing frequently in CI build on unrelated changes

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3298] opened 2022-03-23 01:42 UTC
A recent example: https://github.com/uutils/coreutils/runs/5637336986?check_suite_focus=true

**Comment by tertsdiepraam** [comment] 2022-03-23 10:31
I think this is a duplicate of https://github.com/uutils/coreutils/issues/3171, although the fact that it's still happening makes it clear that fixing this is a priority.

**Closed** 2022-03-24 00:52 UTC
