### ISSUE TITLE
`expr  3 \| 1W + 4` fails when it should return 3

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5406] opened 2023-10-14 13:38 UTC
With our impl:

```
$ ./target/debug/coreutils expr  3 \| 1W + 4
expr: syntax error (first RPN token does not represent the root of the expression AST)
```
(side note, we could improve our default error message here)

With GNU:

```
/usr/bin/expr  3 \| 1W + 4
3
```

**Comment by cakebaker** [comment] 2023-10-14 13:51
Duplicate of https://github.com/uutils/coreutils/issues/5377

**Closed by cakebaker** 2023-10-14 13:51 UTC
Labels: U - expr, good first issue

**Comment by sylvestre** [comment] 2023-10-14 13:55
sorry :)
