### ISSUE TITLE
test flake

### ISSUE THREAD

**Issue by kevinburkemeter** [uutils/coreutils#1668] opened 2020-12-20 05:44 UTC
My PR #1667 just failed with this error: https://github.com/kevinburkemeter/coreutils/runs/1583693370?check_suite_focus=true

```
test test_chown::test_passgrp::test_grp2gid ... error: test failed, to rerun pass '--test tests'

Caused by:
  process didn't exit successfully: `/target/i686-unknown-linux-musl/debug/deps/tests-6390ebd3193ed219` (signal: 11, SIGSEGV: invalid memory reference)
Error: The process '/usr/share/rust/.cargo/bin/cross' failed with exit code 101
```

Given this test changes one line in the `rm` binary, it seems a failure in the `test_chown` library would be unrelated.

**Comment by rivy** [comment] 2020-12-20 05:53
That commit looks to be passing on our [CI run](https://github.com/uutils/coreutils/actions/runs/433439645).
"Invalid memory reference" looks like it could be just a transient "cosmic ray" event. I'd re-run your CI workflow to check it.

I'll close this, but will re-open if it becomes reproducible.

**Closed by rivy** 2020-12-20 05:53 UTC

**Comment by kevinburkemeter** [comment] 2020-12-20 06:06
I guess that is sort of the definition of a flake, is a test that passes sometimes and doesn't pass other times. If you could reproduce it it wouldn't be flaky...

**Comment by rivy** [comment] 2020-12-20 08:57
Ah, I didn't get the reference.

**Comment by sylvestre** [comment] 2020-12-20 09:10
more on it https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html :)
